### ISSUE TITLE
Updating an ID's volume

### ISSUE THREAD

**Issue by ImVexed** [jcornaz/bvh-arena#29]
Hello!

I'm using this to back broad phase collision for a game I'm writing with Bevy. And have entities that frequently move (~30TPS).  

I noticed there isn't a `update()` method, Should I just be `remove()`ing and then `insert()`ing every time an index's volume has shifted? Thanks!

**Comment by jcornaz** [comment]
> I noticed there isn't a update() method, Should I just be remove()ing and then insert()ing every time an index's volume has shifted?

Yes. You remove and re-add.

We could *technically* implement an update method, but not worth it IMO, as it is kind of complicated especially if we want to keep the tree balanced, and `remove` + `add` work just fine. However, I should probably clarify that in the documentation.

With Bevy, what I find the best is to have a system that removes all entities that have moved, and then another system that re-add all of them (instead of add/remove per entity). That should should keep the bvh reasonably balanced without the need for a dedicated `balance` method nor any complicated logic.

**Comment by ImVexed** [comment]
Hm, I worry that splitting removing/adding entities into the BVH could introduce a state where another system gets ahold of an entity that lacks BVH backing because we're after the removal but before the add system. 

Thanks for the info though!

As a random aside, have you ever considered collision masking? Or should that be carried out by narrow phase?

**Comment by jcornaz** [comment]
> Hm, I worry that splitting removing/adding entities into the BVH could introduce a state where another system gets ahold of an entity that lacks BVH backing because we're after the removal but before the add system. So I'll probably do it in a single system for now.

Good point indeed! My point was mostly to *remove all* then *add all* (instead of *add/remove on each*). But a single system with two loops is probably better indeed, I agree.

> As a random aside, have you ever considered collision layer masking? Or should that be carried out by narrow phase?

Currently, I am personally checking that *between* the broad and narrow phases. Sometimes, I also create multiple broad phase tracking structures to segregate entities that can never collide.

But yes, layer masking may be a legitimate feature for this project. I'd have to think more about it and come up with an idea for the interface. However, I don't know if I'll find time for that any time soon, as my current project is using a grid for the broad phase, not a bvh. But I am open to contributions :-)
